apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rmg-platform-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "rmg-platform-service"
spec:
  tls:
    - hosts:
        - play.rmgplatform.com
      secretName: rmg-platform-tls
  rules:
    - host: play.rmgplatform.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rmg-platform-service
                port:
                  number: 80
